### ISSUE TITLE
cfg = layer.options('basic') - module object has no attribute 'options'

### ISSUE THREAD

**Issue by andrewdmcleod** [juju-solutions/reactive-base-layer#21]
unit-hue-3[4047]: 2016-01-12 15:40:05 INFO unit.hue/3.install logger.go:40   File "lib/charms/bootstrap.py", line 31, in install_charm_deps
unit-hue-3[4047]: 2016-01-12 15:40:05 INFO unit.hue/3.install logger.go:40     cfg = layer.options('basic')
unit-hue-3[4047]: 2016-01-12 15:40:05 INFO unit.hue/3.install logger.go:40 AttributeError: 'module' object has no attribute 'options'

**Comment by johnsca** [comment]
This was a conflict with this base layer and the hadoop-client base layer: https://github.com/juju-solutions/layer-hadoop-client/pull/1
