### ISSUE TITLE
Hooks are Python2

### ISSUE THREAD

**Issue by stub42** [juju-solutions/reactive-base-layer#5]
'#!/bin/env python' will be Python2, and remain so until Python2 disappears from the default install.

We really, really should be encouraging Python3 work rather than encouraging tech-debt.

This issue also exists in charm-tools, as perhaps 'charm build' should correct shebang lines and make them consistent across layers and I think it is somehow responsible for installing the correct charm-helpers and charms.reactive dependencies.

**Comment by johnsca** [comment]
Addressed in #10
